// <auto-generated />
using CraftU.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CraftU.Migrations
{
    [DbContext(typeof(CraftUContext))]
    [Migration("20230802180451_InitialUpdateClassName")]
    partial class InitialUpdateClassName
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CraftU.Models.CraftCourse", b =>
                {
                    b.Property<int>("CraftCourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CourseDate")
                        .HasColumnType("longtext");

                    b.Property<string>("CourseName")
                        .HasColumnType("longtext");

                    b.HasKey("CraftCourseId");

                    b.ToTable("CraftCourses");
                });

            modelBuilder.Entity("CraftU.Models.Supply", b =>
                {
                    b.Property<int>("SupplyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CraftCourseId")
                        .HasColumnType("int");

                    b.Property<int>("SupplyCost")
                        .HasColumnType("int");

                    b.Property<string>("SupplyName")
                        .HasColumnType("longtext");

                    b.HasKey("SupplyId");

                    b.HasIndex("CraftCourseId");

                    b.ToTable("Supplies");
                });

            modelBuilder.Entity("CraftU.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CraftCourseId")
                        .HasColumnType("int");

                    b.Property<string>("StudentName")
                        .HasColumnType("longtext");

                    b.HasKey("StudentId");

                    b.HasIndex("CraftCourseId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("CraftU.Models.Supply", b =>
                {
                    b.HasOne("CraftU.Models.CraftCourse", null)
                        .WithMany("Supplies")
                        .HasForeignKey("CraftCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CraftU.Student", b =>
                {
                    b.HasOne("CraftU.Models.CraftCourse", null)
                        .WithMany("Students")
                        .HasForeignKey("CraftCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CraftU.Models.CraftCourse", b =>
                {
                    b.Navigation("Students");

                    b.Navigation("Supplies");
                });
#pragma warning restore 612, 618
        }
    }
}
